image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "--batch-mode -P headless"

stages:
  - test
  - build

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

test:
  stage: test
  script:
    - mvn clean test -f todolist/pom.xml "-DskipUiTests=true"

build:
  stage: build
  when: manual
  script:
    - mvn clean install -f todolist/pom.xml "-DskipUiTests=true"
